POST http://localhost:8080/api/security/login
Content-Type: application/json

{
    "username": "june",
    "password":"admin-password"
}

#####################################################

DELETE http://localhost:8080/api/todo/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0b2RvLWFwcCIsInN1YiI6Imp1bmUiLCJhdXRob3JpdGllcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2NDk0Mjg5OTZ9.QLIKxzBpN5qKVkfYq0Q24Rv6Ydxczdy_vWCBILoWZE8

